const list = [
  {
    id: 1,
    date: "11 Nov, 2021",
    title: "Hammer",
    details: "This is a hammer to do work with ",
    status: "Alright",
    quantity: "200/300",
    unitPrice: 10,
    amount: 2000,
  },
  {
    id: 2,
    date: "10 Nov, 2021",
    title: "Hammer",
    details: "This is a screw to do work with ",
    status: "Alright",
    quantity: "100/230",
    unitPrice: 10,
    amount: 150,
  },
  {
    id: 3,
    date: "9 Nov, 2021",
    title: "Hammer",
    details: "Wood plan will be used to to woodworks",
    status: "In Progress",
    quantity: "122/240",
    unitPrice: 15,
    amount: 240,
  },
  {
    id: 4,
    date: "8 Nov, 2021",
    title: "Hammer",
    details: " -",
    status: "Out of stock",
    quantity: "0/200",
    unitPrice: 10,
    amount: "0.00",
  },
  {
    id: 5,
    date: "7 Nov, 2021",
    title: "Hammer",
    details: "- ",
    status: "Out of stock",
    quantity: "0/200",
    unitPrice: 15,
    amount: "0.00",
  },
  {
    id: 6,
    date: "6 Nov, 2021",
    title: "Hammer",
    details: "This is a hammer to do work with ",
    status: "Alright",
    quantity: 200,
    unitPrice: 10,
    amount: 2000,
  },
  {
    id: 7,
    date: "5 Nov, 2021",
    title: "Hammer",
    details: "This is a hammer to do work with ",
    status: "In Progress",
    quantity: "200/300",
    unitPrice: 10,
    amount: 2000,
  },
];

export default list;
